RealEskalate/2023-project-phase-starter-projects

- aait/backend/group-1B/Domain/Common/BaseEntity.cs
- aait/backend/group-1B/Domain/Entities/Follow.cs
- aait/backend/group-1B/Domain/Entities/User.cs
I have defined user and follow entities
> Add(AAiT-backend-1B) : Add user and follow entities

- aait/web/group-3/starter_project_group3/app/globals.css
- aait/web/group-3/starter_project_group3/tailwind.config.ts
We have added colors and font that are going to be used in the future.
> setup(AAiT-web_g3): tailwind configuration

- aait/mobile/group-2/blog_app/lib/features/user/data/models/user_data_model.dart
- aait/mobile/group-2/blog_app/macos/Flutter/GeneratedPluginRegistrant.swift
- aait/mobile/group-2/blog_app/pubspec.yaml
Added User Data model - please review it
> feat(AAiT-mobile-2): Add User Data Model

- aait/mobile/group-2/blog_app/lib/features/user/domain/repositories/user_repository.dart
- aait/mobile/group-2/blog_app/lib/features/user/domain/usecases/user_usecases/get_user_data_usecase.dart
- aait/mobile/group-2/blog_app/lib/features/user/domain/usecases/user_usecases/update_user_photo_usecase.dart
User entity domain layer usecase and repository is added.
- getUserData usecase
-  updateUserPhoto usecase
> feat(AAiT.mobile.g2): user usercase and repository

- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/local/local_datasource.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/local/local_datasource_impl.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/models/article_model.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/models/tag_model.dart
- aait/mobile/group-2/blog_app/lib/features/article/domain/entities/article.dart
- aait/mobile/group-2/blog_app/lib/features/article/domain/entities/tag.dart
Added local data source
- uses shared_preferences 
Added article and tag model
> feat(AAiT-mobile-2): Add Article Local Data Source

- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote_datasource.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote_datasource_impl.dart
- aait/mobile/group-2/blog_app/pubspec.yaml
- Add Article Remote Data Source Contract
- Add Article Remote Data Source Implementation
- Add http client dependency
> feat(AAiT-mob-2): Add Article Remote Data Source Implementation

- aastu/web/group-1/a2sv-blogs/next.config.js
- aastu/web/group-1/a2sv-blogs/src/app/blogs/[id]/page.tsx
> feat(AASTU-web-1): Added single blog view

- aastu/mobile/group-2/blog_application/lib/features/blog/presentation/pages/auth.dart
add login and registration screen
> feat(mobile): add authentication page

- aastu/mobile/group-2/blog_application/lib/features/blog/domain/repositories/article_repository.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/domain/repositories/auth_repository.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/domain/usecases/login_usecase.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/domain/usecases/register_usecase.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/presentation/blocs/auth/auth_bloc.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/presentation/blocs/auth/auth_event.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/presentation/blocs/auth/auth_state.dart
- add authentication **usecases** 
- add authentication **bloc**  
- update repository **abstract classes**
> feat(mobile) Add bloc and usecase for authentication

- aastu/mobile/group-2/blog_application/lib/core/usecases/usecase.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/domain/usecases/get_article.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/domain/usecases/get_articles.dart
- aastu/mobile/group-2/blog_application/lib/features/blog/domain/usecases/get_tags.dart
please take your time to review it
> Fix(Mobile): Add usecases for article fetch

- aait/mobile/group-2/blog_app/lib/core/error/exception.dart
- aait/mobile/group-2/blog_app/lib/core/error/failure.dart
- aait/mobile/group-2/blog_app/lib/core/network/network_info.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote_datasource_impl.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/repositories/article_repository_impl.dart
- aait/mobile/group-2/blog_app/pubspec.yaml
- Add article repository
- Add network information
- Add internet_connection_checker (external dependency)
- Add new failure types
> feat(AAiT-mobile-2): Add Article Repository Implementation

- aait/web/group-3/starter_project_group3/components/footer/Footer.tsx
- aait/web/group-3/starter_project_group3/types/footerNav/footerNav.ts
We have added footer page. and here are the main changes that we make
- component/footer:  Footer page is added here
- public/assets:  Added SVG files that are used in the footer page
> fix(AAiT-web_g3): confict on Footer.tsx is resolved

- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/local/user_local_data_source.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/local/user_local_data_source_impl.dart
Added user local data source - please review it
> feat(AAiT-mobile-2): Add User Local data source

- aait/backend/group-1B/Application.Tests/Application.Tests.csproj
- aait/backend/group-1B/Application/Application.csproj
- aait/backend/group-1B/Application/Contracts/Persistence/INotificationRepository.cs
- aait/backend/group-1B/Application/DTOs/Notifications/GetNotificationDto.cs
- aait/backend/group-1B/Application/DTOs/Notifications/Validators/GetNotificationDtoValidator.cs
- aait/backend/group-1B/Application/DTOs/Posts/Validators/NotificationDto.cs
- aait/backend/group-1B/Application/Features/Notifications/Handlers/Commands/CreateNotificationRequestHandler.cs
- aait/backend/group-1B/Application/Features/Notifications/Handlers/Queries/GetAllNotificationRequestHandler.cs
- aait/backend/group-1B/Application/Features/Notifications/Requests/Commands/CreateNotificationRequest.cs
- aait/backend/group-1B/Application/Features/Notifications/Requests/Commands/DeleteNotificationRequest.cs
- aait/backend/group-1B/Application/Features/Notifications/Requests/Queries/GetAllNotifiactionsRequest.cs
- aait/backend/group-1B/Domain/Domain.csproj
- aait/backend/group-1B/Domain/Entities/Notification.cs
- aait/backend/group-1B/Domain/Entities/User.cs
- aait/backend/group-1B/Infrastructure/Infrastructure.csproj
- aait/backend/group-1B/Persistence/Persistence.csproj
- aait/backend/group-1B/WebApi/WebApi.csproj
> Add(AAiT-backend-1b): Notification feature

- aait/mobile/group-2/blog_app/lib/core/network/custom_client.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote_datasource_impl.dart
- Created Custom Http Client Wrapper
- Added authToken on remote data source
> feat(AAiT-mobile-2): Create Custom Http Client

- aastu/web/group-2/app/components/profile/AccountSettingsSection.tsx
- aastu/web/group-2/app/profile/accountsetting/page.tsx
- aastu/web/group-2/app/profile/layout.tsx
- aastu/web/group-2/lib/redux/slices/loginSlice.ts
> feat(AASTU.web.G2): Finished account settings

- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/user_remote_data_source.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/user_remote_data_source_impl.dart
- aait/mobile/group-2/blog_app/lib/features/user/domain/repositories/user_repository.dart
- aait/mobile/group-2/blog_app/lib/features/user/domain/usecases/user_usecases/get_user_data_usecase.dart
- aait/mobile/group-2/blog_app/lib/features/user/domain/usecases/user_usecases/update_user_photo_usecase.dart
User remote data source implementation added
> feat(Aait.mob.g2): add user remote data source

- aait/backend/group-2B/.editorconfig
> feat(backend-group-2): add config files

- aait/mobile/group-1/blog_app/android/gradle/wrapper/gradle-wrapper.properties
- aait/mobile/group-1/blog_app/lib/core/errors/failures/exception.dart
- aait/mobile/group-1/blog_app/lib/core/errors/failures/failure.dart
- aait/mobile/group-1/blog_app/lib/core/errors/failures/server_failure.dart
- aait/mobile/group-1/blog_app/lib/core/utils/app_dimension.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/data_source/auth_local_data_source.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/data_source/auth_local_data_source_Impl.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/data_source/auth_remote_data_source.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/data_source/auth_remote_data_source_Impl.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/models/login_user_model.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/models/sign_up_user_model.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/models/user_data_model.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/data/repository/auth_repository_Impl.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/domain/entities/login_user_entitiy.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/domain/entities/sign_up_user_entity.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/domain/entities/user_data_entity.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/domain/repositories/auth_repository.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/domain/usecases/login_use_case.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/domain/usecases/sign_up_use_case.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/domain/usecases/user_use_case.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/presentation/bloc/sign_in_bloc/event.dart
- aait/mobile/group-1/blog_app/lib/features/authentication_and_authorization/presentation/pages/signup_login_page.dart
- aait/mobile/group-1/blog_app/lib/features/user_profile/data/models/user_model.dart
- aait/mobile/group-1/blog_app/pubspec.lock
I have added authentication and authorization.please review
> feat(aait-mobile-g1): authentication and authoziation added

- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/local/user_local_data_source.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/local/user_local_data_source_impl.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/repositories/user_repository_impl.dart
- aait/mobile/group-2/blog_app/lib/features/user/domain/repositories/user_repository.dart
- aait/mobile/group-2/blog_app/lib/features/user/domain/usecases/user_usecases/get_bookmarked_articles_usecase.dart
Added User repository implementation
Added getBookmarkedarticles usecase
Updated user repository implementation with getBookmarkedArticles usecase
Add cacheUser and getUser to user local data source
Please review it
> Aait.mobile.g2.nathan zelalem.repository implementation

- aait/mobile/group-2/blog_app/lib/features/article/domain/usecases/usecases.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/bloc/article_bloc.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/bloc/article_event.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/bloc/article_state.dart
- aait/mobile/group-2/blog_app/pubspec.yaml
- Added `flutter_bloc` (External dependency)
- Created Article bloc, events and states
> feat(AAiT-mobile-2): Add Article Bloc

- aastu/web/group-1/a2sv-blogs/src/components/teams/PaginationButtons.tsx
- aastu/web/group-1/a2sv-blogs/src/components/teams/TeamHome.tsx
- aastu/web/group-1/a2sv-blogs/src/components/teams/TeamMemberCard.tsx
- aastu/web/group-1/a2sv-blogs/src/components/teams/TeamMemberList.tsx
- aastu/web/group-1/a2sv-blogs/src/types/TeamMember.ts
This is a new branch. I copied the files here then tried to match the main. Hope it works now.
> aastu.web.g1.wossen-ruth.team-page

- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/local/local.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote.dart
- aait/mobile/group-2/blog_app/lib/injection_container.dart
- aait/mobile/group-2/blog_app/pubspec.yaml
Summary of changes:
- Add dependency injection
- Add get_it (external package)
> feat(AAiT-mobile-2): Add Dependency Injection

- aastu/web/group-1/a2sv-blogs/next.config.js
- aastu/web/group-1/a2sv-blogs/package-lock.json
- aastu/web/group-1/a2sv-blogs/package.json
- aastu/web/group-1/a2sv-blogs/src/app/blogs/create/page.tsx
- aastu/web/group-1/a2sv-blogs/src/components/blogs/QuillForm.tsx
- aastu/web/group-1/a2sv-blogs/src/components/blogs/TagsSelector.tsx
It has not been completed, but is being pushed so that we can start integration early, It is rather easy to edit this page afterwards
> feat(aastu-web-g1): Created the basic layout of add blog page

- aait/mobile/group-3/blog_app/lib/core/color/colors.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/article_icon_button.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/article_info_widget.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/basic_information_widget.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/button_container.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/post_content.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/profile_image.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/row_button.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/title_bar.dart
> fix(AAiT-Mobile-3): fix color variables

- aait/mobile/group-3/blog_app/lib/features/article/presentation/screen/article_reading.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/screen/test.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/screen/write_aricle_page.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/test.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/add_tags_text_field.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/article_content_text_field.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/custom_app_bar.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/custom_elevated_button.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/custom_text_field.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/form_submit_button.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/head_title.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/post_image.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/post_text.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/test.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/user_info.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/white_gradient_overlay.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/widgets.dart
- aait/mobile/group-3/blog_app/pubspec.yaml
**PR Description:**
🚀 **New UI Screens and Code Refactoring**
This pull request introduces two new UI screens, "article_reading.dart" and "write_article_page.dart", along with a comprehensive code refactoring effort to enhance code maintainability and cleanliness. 
**Changes Made:**
- Created "article_reading.dart" screen to facilitate article reading.
- Developed "write_article_page.dart" screen for writing articles.
- Utilized `flutter_screen_util` package to ensure responsiveness across various device sizes and orientations
- Implemented a systematic refactoring process to break down the code into reusable widget components.
[Figma Link](https://www.figma.com/file/7JEAmCrBGCYJl4XresRNtf/A2SV---internship---Learning-Project?type=design&node-id=0%3A1&mode=design&t=Otliept4LRzqK1Z2-1) …
> feat(AAiT-mobile-3): Add Article Reading and Writing Page

- aait/mobile/group-3/blog_app/lib/features/auth/domain/entity/auth_entitie.dart
- aait/mobile/group-3/blog_app/lib/features/auth/domain/entity/test.dart
- aait/mobile/group-3/blog_app/lib/features/auth/domain/repository/auth_repository.dart
- aait/mobile/group-3/blog_app/lib/features/auth/domain/repository/test.dart
- aait/mobile/group-3/blog_app/lib/features/auth/domain/use_case/login_usecase.dart
- aait/mobile/group-3/blog_app/lib/features/auth/domain/use_case/signup_usecase.dart
- aait/mobile/group-3/blog_app/lib/features/auth/domain/use_case/test.dart
I implements domain layer for the auth feature
> feat(mobile : g3 ,Yohanes) impl auth domain layer

- aait/mobile/group-3/blog_app/lib/features/article/data/models/article_model.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/models/test.dart
- aait/mobile/group-3/blog_app/lib/features/article/domain/entity/article.dart
- aait/mobile/group-3/blog_app/test/features/article/data/models/article_model_test.dart
- aait/mobile/group-3/blog_app/test/features/article/data/models/test.dart
- aait/mobile/group-3/blog_app/test/fixtures/article.json
- aait/mobile/group-3/blog_app/test/fixtures/fixture_reader.dart
**Implemented Data Layer: Article Model and Tests**
In this pull request, I've started implementing the data layer for the article feature. Here's a summary of the changes:
- Added the `article_model.dart` file to represent article data in the data layer.
- Implemented `fromMap`, `fromJson`, `toMap`, `toJson`, and `copyWith` methods in the `ArticleModel` class to handle data conversion and manipulation.
- Wrote comprehensive unit tests to validate the correctness of these methods. All tests have passed successfully.
Further developments will build upon this data model. Feel free to review and provide feedback. 
Thank you!
> feat(AAiT-mobile-3): Add Article Model and Tests

- aastu/web/group-2/app/components/home/LandingSection.tsx
- aastu/web/group-2/app/page.tsx
- aastu/web/group-2/app/profile/layout.tsx
- aastu/web/group-2/app/profile/page.tsx
> aastu.web.g2.natanim ashenafi.some cleaning up

- aait/web/group-3/starter_project_group3/package.json
- aait/web/group-3/starter_project_group3/store/features/blog-detail/blog-detail.ts
- aait/web/group-3/starter_project_group3/store/features/blogs/blogs-api.ts
- aait/web/group-3/starter_project_group3/store/features/create-blog/create-blog-api.ts
- aait/web/group-3/starter_project_group3/tailwind.config.ts
- aait/web/group-3/starter_project_group3/types/blog/blog.ts
- Added blogs api, blog detail api, and create blog api 
- Modified the package.json and tailwind.config.ts files 
- Modified the blog.ts file under types folder
> feat(aait.web.g3):Add blogs api, blog detail api and create blog api

- aait/mobile/group-2/blog_app/lib/features/authentication/data/data_sources/remote_data_source.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/data/data_sources/remote_data_source_impl.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/data/models/authenticated_user_info_model.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/domain/entities/authenticated_user_info.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/presentation/bloc/auth_bloc.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/presentation/bloc/auth_event.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/presentation/bloc/auth_state.dart
I have implemented bloc for authentication feature with the following changes:
- updated authenticated_user_info entity: made the image and imageClouidnaryPublicId fields named optional argument
- updated authenticated_user_info model: made the image and imageClouidnaryPublicId fields named optional argument
- updated auth remote data source: fixed the imports
- implemented authentication bloc events
- implemented authentication bloc states
- implemented authentication bloc
**Please review it.**
> feat(aait-mobile-g2): implement bloc for authentication feature

- aait/mobile/group-2/blog_app/lib/features/user/presentation/bloc/user_bloc.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/bloc/user_event.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/bloc/user_state.dart
add user feature bloc implementation
> feat(AAiT.mob.g2): add user bloc

- aait/mobile/group-3/blog_app/lib/core/error/exception.dart
- aait/mobile/group-3/blog_app/lib/core/error/failure.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/data_sources/local_data_source.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/data_sources/remote_data_source.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/data_sources/test.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/models/auth_entite_model.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/models/test.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/repository/auth_repository_impl.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/repository/test.dart
I implemente the data layer of the auth feature
> Yohanse.auth.data

- aait/web/group-3/starter_project_group3/app/login/page.tsx
- aait/web/group-3/starter_project_group3/app/register/page.tsx
login and Register pages are completed. and here are the changes we made
- app/login: Contains login page
- app/register: Contains login page
- 
here are sample screenshots.
> feat(AAiT-web_g3): add login and register page

- aait/mobile/group-3/blog_app/lib/blog_app.dart
- aait/mobile/group-3/blog_app/lib/features/onboarding/screens/onboarding_page.dart
- aait/mobile/group-3/blog_app/lib/features/onboarding/screens/splash_screen.dart
- aait/mobile/group-3/blog_app/lib/features/onboarding/widgets/on-boarding_images.dart
- aait/mobile/group-3/blog_app/lib/features/onboarding/widgets/scrollable_content.dart
- aait/mobile/group-3/blog_app/pubspec.yaml
-implemented the splash screen and the onboarding pages
> aait.mobile.g3.abinet_onboarding_pages

- aait/mobile/group-3/blog_app/lib/features/auth/presentation/bloc/login_bloc/bloc/login_bloc.dart
- aait/mobile/group-3/blog_app/lib/features/auth/presentation/bloc/login_bloc/bloc/login_event.dart
- aait/mobile/group-3/blog_app/lib/features/auth/presentation/bloc/login_bloc/bloc/login_state.dart
- aait/mobile/group-3/blog_app/lib/features/auth/presentation/bloc/signup_bloc/bloc/signup_bloc.dart
- aait/mobile/group-3/blog_app/lib/features/auth/presentation/bloc/signup_bloc/bloc/signup_event.dart
- aait/mobile/group-3/blog_app/lib/features/auth/presentation/bloc/signup_bloc/bloc/signup_state.dart
- aait/mobile/group-3/blog_app/lib/features/auth/presentation/bloc/test.dart
I implemented bloc for auth feature presentation layer
> feat(AAit-mobile-g3): add presentaion bloc layer

- aait/web/group-3/starter_project_group3/app/blogs/[id]/page.tsx
- aait/web/group-3/starter_project_group3/components/commons/Error.tsx
- aait/web/group-3/starter_project_group3/components/commons/Loading.tsx
- Added blog detail page
- Added Error and Loading components
> feat(aait.web.g3): Add blog detail page

- aait/web/group-3/starter_project_group3/app/profile/accountsetting/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/personalinformation/page.tsx
- aait/web/group-3/starter_project_group3/components/blog/SmallBlogCard.tsx
- aait/web/group-3/starter_project_group3/components/footer/Footer.tsx
Profile related pages are completed.
> feat(AAiT-web_g3): pofile pages added

- aait/mobile/group-3/blog_app/lib/core/util/app_colors.dart
- aait/mobile/group-3/blog_app/lib/core/util/theme_utils.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/bloc/test.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/screen/home_screen.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/blog_card_widget.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/header_widget.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/search_bar_widget.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/tags_widget.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/article_info_widget.dart
**Description:**
This PR introduces the HomePage screen, the central hub of the blog app. It features article listings, a search bar, a header, and a new article addition button.
**Changes:**
1. Created the HomePage widget to serve as the primary app screen.
2. Integrated the SearchBarWidget for article search and filtering.
3. Added the HeaderWidget for user interactions and sorting.
4. Incorporated the BlogCardWidget to display individual articles.
> Ketema.homepage

- aait/mobile/group-3/blog_app/lib/blog_app.dart
- aait/mobile/group-3/blog_app/lib/features/onboarding/screens/onboarding_page.dart
- aait/mobile/group-3/blog_app/lib/features/profile/data/data_sources/profile_local_data_source.dart
- aait/mobile/group-3/blog_app/lib/features/profile/data/data_sources/profile_remote_data_source.dart
- aait/mobile/group-3/blog_app/lib/features/profile/data/models/profile_model.dart
- aait/mobile/group-3/blog_app/lib/features/profile/data/repository/profile_repository_impl.dart
- aait/mobile/group-3/blog_app/lib/features/profile/domain/entity/profile.dart
- aait/mobile/group-3/blog_app/lib/features/profile/domain/repositories/profile_repository.dart
- aait/mobile/group-3/blog_app/lib/features/profile/domain/repository/test.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/bloc/profile_bloc.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/article_info_widget.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/grid_view_article_card.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/list_view_article_card.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/post_content.dart
- aait/mobile/group-3/blog_app/lib/features/profile/presentation/widgets/row_button.dart
- aait/mobile/group-3/blog_app/lib/injection_container.dart
- aait/mobile/group-3/blog_app/lib/main.dart
- aait/mobile/group-3/blog_app/pubspec.yaml
- aait/mobile/group-3/blog_app/test/features/profile/data/models/profile_model_test.dart
- aait/mobile/group-3/blog_app/test/features/profile/data/repository/profile_repository_impl_test.dart
- aait/mobile/group-3/blog_app/test/features/profile/domain/use_case/get_profile_test.dart
- aait/mobile/group-3/blog_app/test/features/profile/domain/use_case/update_profile_picture_test.dart
- aait/mobile/group-3/blog_app/test/fixtures/profile.json
Added a functional dependency injection so that the bloc can take data from backend
- Removed the dummy data from the bloc file and added the usecase GetProfile for bloc
please review.
> feat(AAiT-Mobile-3): Add functional dep. injection

- aait/backend/group-2B/Application/Common/Exceptions/BadRequestException.cs
- aait/backend/group-2B/Application/Common/Exceptions/NotFoundException.cs
- aait/backend/group-2B/Application/Common/Exceptions/ValidationException.cs
- aait/backend/group-2B/Application/Common/Responses/BaseCommandResponse.cs
- aait/backend/group-2B/Application/Common/Responses/CommonResponse.cs
- aait/backend/group-2B/Application/Contracts/Persistence/IInteractionRepository.cs
- aait/backend/group-2B/Application/DTOs/InteractionDTOs/CommentDTOs/DeleteCommentDTO.cs
- aait/backend/group-2B/Application/DTOs/InteractionDTOs/CommentDTOs/UpdateCommentDTO.cs
- aait/backend/group-2B/Application/DTOs/InteractionDTOs/CommentDTOs/Validator/DeleteCommentDTOValidator.cs
- aait/backend/group-2B/Application/DTOs/InteractionDTOs/CommentDTOs/Validator/UpdateCommentDTOValidator.cs
- aait/backend/group-2B/Application/DTOs/InteractionDTOs/InteractionDto.cs
- aait/backend/group-2B/Application/DTOs/InteractionDTOs/Validator/CommentDtoValidator.cs
- aait/backend/group-2B/Application/DTOs/InteractionDTOs/Validator/likeDTOValidator.cs
- aait/backend/group-2B/Application/Features/Interactions/Handlers/Commands/CreateCommentInteractionCommandHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Handlers/Commands/DeleteCommentInteractionCommandHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Handlers/Commands/LikeUnlikePostInteractionCommandHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Handlers/Commands/UpdateCommentInteractionCommandHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Handlers/Queries/GetAllCommentInteractionRequestHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Handlers/Queries/GetInteractionRequestHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Commands/CreateCommentInteractionCommand.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Commands/DeleteCommentInteractionCommand.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Commands/LikeUnlikePostInteractionCommand.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Commands/UpdateCommentInteractionCommand.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Queries/GetAllCommentInteractionRequest.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Queries/GetInteractionRequest.cs
- aait/backend/group-2B/Persistence/Repositories/InteractionRepository.cs
- aait/backend/group-2B/WebApi/Controllers/InteractionsController.cs
I have implemented the interaction entity and all its feature.
> fixed the issues mentioned in the previous pr

- aait/web/group-3/starter_project_group3/app/blogs/[id]/page.tsx
- aait/web/group-3/starter_project_group3/app/blogs/create/page.tsx
- aait/web/group-3/starter_project_group3/app/blogs/page.tsx
- aait/web/group-3/starter_project_group3/components/blog/ReduxProvider.tsx
- Fixed the blogs list page
- Replaced the dummy data with the real API data
> Aait.web.g3.yohannes ahunm.blogs list

- aastu/web/group-2/app/blog/add-blog/page.tsx
- aastu/web/group-2/app/components/profile/AccountSettingsSection.tsx
- aastu/web/group-2/app/components/profile/MyblogCard.tsx
- aastu/web/group-2/app/profile/page.tsx
> fix(AASTU-web-G2): Fix some bugs and add success messages

- aait/mobile/group-2/blog_app/lib/features/user/presentation/screens/user_profile.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/article_grid_view.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/article_list_view.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/gradient_at_bottom.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/posts_bar.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/profile_bar.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/show_posts_and_bookmarks.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/show_posts_or_bookmarks_button.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/single_article_post_grid_view.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/single_article_post_list_view.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/user_bio.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/user_profile_details.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/user_profile_info.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/user_profile_photo.dart
Added user profile ui
Made the widgets responsive by using screen_util
Please review it
> feat(AAiT-mobile-2): User Profile UI

- aait/mobile/group-2/blog_app/lib/core/constants/constants.dart
- aait/mobile/group-2/blog_app/lib/core/network/custom_client.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/local/local_datasource.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/local/local_datasource_impl.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote_datasource.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote_datasource_impl.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/models/article_mapper.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/models/article_model.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/models/dto/create_article_dto.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/repositories/article_repository_impl.dart
- aait/mobile/group-2/blog_app/lib/features/article/domain/repositories/article_repository.dart
- aait/mobile/group-2/blog_app/lib/features/article/domain/usecases/get_tags.dart
- aait/mobile/group-2/blog_app/lib/features/article/domain/usecases/usecases.dart
Summary of changes:
Tag:
- Add get tags use case
- Add get and cache tags to remote and local data source
Custom Client:
- Add multipart request capability to `CustomClient` to support image upload
Data sources:
- Add `CreateArticleDto` 
- Add Article to ArticleModel Mapper
Constants:
- Fix API base URL
> feat(AAiT-mobile-2): Add Get Tag Use case and Repository

- aait/backend/group-1B/Application.Tests/Application.Tests.csproj
- aait/backend/group-1B/Application.Tests/Features/Users/Command/FollowUserRequestHandlerUnitTest.cs
- aait/backend/group-1B/Application.Tests/Features/Users/Command/UnFollowUserRequestHandlerUnitTest.cs
- aait/backend/group-1B/Application.Tests/Features/Users/Command/UpdateUserRequestHandlerUnitTest.cs
- aait/backend/group-1B/Application.Tests/Features/Users/Queries/GetFollowersRequestHandlerUnitTest.cs
- aait/backend/group-1B/Application.Tests/Features/Users/Queries/GetUserDetailHandlerUnitTest.cs
- aait/backend/group-1B/Application.Tests/Mocks/MockUserRepository.cs
- aait/backend/group-1B/Application/Contracts/Persistence/IUserRepository.cs
- aait/backend/group-1B/Application/DTOS/Users/FollowDto.cs
- aait/backend/group-1B/Application/DTOS/Users/UpdateUserDto.cs
- aait/backend/group-1B/Application/DTOS/Users/UserDetail.cs
- aait/backend/group-1B/Application/DTOS/Users/UserListDto.cs
- aait/backend/group-1B/Application/DTOS/Users/Validation/UpdateUserDtoValidator.cs
- aait/backend/group-1B/Application/Features/Posts/Handlers/Queries/GetPostsByUserIdRequestHandler.cs
- aait/backend/group-1B/Application/Features/Users/Handler/Command/FollowUserRequestHandler.cs
- aait/backend/group-1B/Application/Features/Users/Handler/Command/UnfollowUserRequestHandler.cs
- aait/backend/group-1B/Application/Features/Users/Handler/Command/UpdateUserRequestHandler.cs
- aait/backend/group-1B/Application/Features/Users/Handler/Queries/GetUserDetailRequestHandler.cs
- aait/backend/group-1B/Application/Features/Users/Handler/Queries/GetUsersRequestHandler.cs
- aait/backend/group-1B/Application/Features/Users/Request/GetUserDetailRequest.cs
- aait/backend/group-1B/Application/Features/Users/Request/GetUsersRequest.cs
- aait/backend/group-1B/Application/Features/Users/Request/command/FollowUserRequest.cs
- aait/backend/group-1B/Application/Features/Users/Request/command/UnfollowUserRequest.cs
- aait/backend/group-1B/Application/Features/Users/Request/command/UpdateUserRequest.cs
- aait/backend/group-1B/Application/Profiles/MappingProfile.cs
- aait/backend/group-1B/Domain/Entities/User.cs
- aait/backend/group-1B/Persistence/Persistence.csproj
- aait/backend/group-1B/Persistence/Repositories/UserRepository.cs
- aait/backend/group-1B/WebApi/Controllers/UserController.cs
- aait/backend/group-1B/WebApi/appsettings.json
follow and unfollow features with unit test
> Aait.bac.1b.sahib.semahegn.follow.unfollow.feature

- aait/mobile/group-3/blog_app/lib/features/auth/data/data_sources/remote_data_source.dart
- aait/mobile/group-3/blog_app/lib/features/auth/data/repository/auth_repository_impl.dart
- aait/mobile/group-3/blog_app/lib/features/profile/data/data_sources/profile_remote_data_source.dart
> fix(AAiT-mobile-3): merge fix

- aait/mobile/group-3/blog_app/lib/core/util/constants.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/data_sources/article_remote_datasource.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/data_sources/test.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/models/article_model.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/models/user_model.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/repository/article_repository_impl.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/repository/test.dart
- aait/mobile/group-3/blog_app/test/features/article/data/models/article_model_test.dart
🔀 Pull Request Description:
This pull request brings substantial updates to the data layer of the application, enhancing its structure and functionality. Here's an overview of the key changes:
🛠 Changes Made:
- Added the `UserModel` to represent user details.
- Enhanced the `ArticleModel` to utilize the updated `UserModel` for article authors.
- Implemented the `ArticleRepository` to manage article data interactions.
- Introduced the `ArticleRemoteDataSourceImpl` to handle remote data operations for articles.
> feat(AAiT-mobile-3): update data layer

- aait/web/group-3/starter_project_group3/app/login/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/accountsetting/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/myblogs/page.tsx
- aait/web/group-3/starter_project_group3/app/register/page.tsx
- aait/web/group-3/starter_project_group3/components/blog/SmallBlogCard.tsx
- aait/web/group-3/starter_project_group3/components/header/Header.tsx
- aait/web/group-3/starter_project_group3/components/header/NavBar.tsx
- aait/web/group-3/starter_project_group3/components/header/NavBarMobile.tsx
- aait/web/group-3/starter_project_group3/next.config.js
- aait/web/group-3/starter_project_group3/store/features/auth/index.ts
- aait/web/group-3/starter_project_group3/types/nav/Nav.ts
login, register, logout functionalites are added and navbar also rendered based on user login status
> feat(AAiT-web_g3): login and register integraton with navbar

- aait/mobile/group-3/blog_app/lib/core/util/constants.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/data_sources/article_remote_datasource.dart
- aait/mobile/group-3/blog_app/lib/features/article/data/repository/article_repository_impl.dart
- aait/mobile/group-3/blog_app/lib/features/article/domain/repository/article_repository.dart
- aait/mobile/group-3/blog_app/lib/features/article/domain/use_case/create_article.dart
- aait/mobile/group-3/blog_app/lib/features/article/domain/use_case/update_article.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/bloc/article_bloc.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/bloc/article_event.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/bloc/article_state.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/widgets/custom_elevated_button.dart
- aait/mobile/group-3/blog_app/test/features/article/presentation/bloc/article_bloc_test.dart
- aait/mobile/group-3/blog_app/test/features/profile/data/repository/profile_repository_impl_test.dart
🔀 Pull Request Description:
This pull request brings some updates to the data and domain layer of the application, enhancing its structure and functionality. Here's an overview of the key changes:
🛠 Changes Made:
- Used image picker to upload image and used XFile datatype for images
- Fix bugs on remote data source
> fix(AAiT-mobile-3): update data and domain layer

- aait/backend/group-2B/Application/Features/Interactions/Handlers/Queries/GetAllCommentInteractionRequestHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Handlers/Queries/GetInteractionRequestHandler.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Queries/GetAllCommentInteractionRequest.cs
- aait/backend/group-2B/Application/Features/Interactions/Requests/Queries/GetInteractionRequest.cs
- aait/backend/group-2B/Application/Profiles/InteractionMapperProfile.cs
I have fixed the return types for getinteraction and getallcommentinteraction handlers.
> fix(AAiT-Backend-2b): fixed the response type for get interactions

- aait/mobile/group-2/blog_app/lib/injection_container.dart
> fix(AAiT-mobile-2): Update Injection Container

- aait/mobile/group-3/blog_app/lib/features/article/data/data_sources/article_remote_datasource.dart
- aait/mobile/group-3/blog_app/lib/features/article/presentation/screen/home_screen.dart
- aait/mobile/group-3/blog_app/lib/injection_container.dart
Added Dependency injection for Article feature of the blog app
> feat(AAiT-mobile-3): Article dependency injection

- aait/backend/group-2B/Application/Application.csproj
- aait/backend/group-2B/Application/DTOs/Notifications/INotificationDto.cs
- aait/backend/group-2B/Application/DTOs/Notifications/NotificationDto.cs
- aait/backend/group-2B/Application/DTOs/Notifications/Validators/INotificationDtoValidator.cs
- aait/backend/group-2B/Application/DTOs/Notifications/Validators/NotificationCreateDtoValidator.cs
- aait/backend/group-2B/Domain/Entites/Notification.cs
- aait/backend/group-2B/Persistence/Repositories/UserRepository.cs
- aait/backend/group-2B/Persistence/SocialSyncDbContext.cs
- aait/backend/group-2B/WebApi/Controllers/NotificationsController.cs
- aait/backend/group-2B/WebApi/WebApi.csproj
Add Controllers for notification feature
> fix(AAiT-backend-2B): Add Controllers to Notification feature #185

- aait/backend/group-2B/Persistence/SocialSyncDbContext.cs
> fix(AAiT-backend-2B): add CreatedAt and LastModified properties

- aait/web/group-1/app/blog/[blogId]/page.tsx
- aait/web/group-1/app/globals.css
- aait/web/group-1/app/layout.tsx
- aait/web/group-1/components/layout/Footer.tsx
- aait/web/group-1/next.config.js
- aait/web/group-1/store/features/blogs/blogs.ts
- aait/web/group-1/store/index.ts
- aait/web/group-1/types/Author.ts
- aait/web/group-1/types/Blog.ts
- aait/web/group-1/types/Profile.ts
I have implemented the single blog page and Integrated the footer component into the layout.
> feat(AAiT-web-1): Implement Single Blog page

- aait/web/group-1/app/success-stories/page.tsx
- aait/web/group-1/components/success-stories/Story.tsx
- aait/web/group-1/types/story.ts
finished the success stories page
> feat(aait-web-g1): Add the success stories page

- aait/mobile/group-2/blog_app/lib/features/article/data/datasources/remote/remote_datasource_impl.dart
- aait/mobile/group-2/blog_app/lib/features/article/data/repositories/article_repository_impl.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/bloc/article_bloc.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/screens/article_screen.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/article_card.dart
- Added delete article usecase
> feat(AAiT-mobile-2): Add Delete Article Usecase

- aait/web/group-3/starter_project_group3/app/blogs/page.tsx
- aait/web/group-3/starter_project_group3/app/layout.tsx
- aait/web/group-3/starter_project_group3/app/profile/accountsetting/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/myblogs/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/personalinformation/page.tsx
- aait/web/group-3/starter_project_group3/store/features/my-blogs/index.ts
- aait/web/group-3/starter_project_group3/store/index.ts
- shows myblogs
- refinements on password reset
> Aait.web.g3.dawit andargachew.profile redux

- aait/mobile/group-2/blog_app/lib/core/constants/constants.dart
- aait/mobile/group-2/blog_app/lib/core/network/custom_client.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/bloc/article_state.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/screens/article_screen.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/screens/home_page.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/article_card.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/tag_selector.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/update_article_form.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/data/data_sources/local_data_source.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/data/data_sources/local_data_source_impl.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/data/repositories/auth_repository_impl.dart
- aait/mobile/group-2/blog_app/lib/features/authentication/presentation/bloc/auth_bloc.dart
- aait/mobile/group-2/blog_app/lib/features/onboard/presentation/screens/initial_screen.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/local/user_local_data_source_impl.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/datasources/user_remote_data_source_impl.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/models/user_data_model.dart
- aait/mobile/group-2/blog_app/lib/features/user/data/repositories/user_repository_impl.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/bloc/user_bloc.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/bloc/user_state.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/screens/user_profile.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/article_list_view.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/profile_bar.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/user_profile_details.dart
- aait/mobile/group-2/blog_app/lib/features/user/presentation/widgets/userprofile/user_profile_photo.dart
- Added update profile
- Update authentication flow for logged in user (app directly jumps to articles list page if user is already logged in)
- Add logout
> feat(AAiT-mobile-2): Add Logout and Update Profile Image

- aait/mobile/group-2/blog_app/lib/core/presentation/util/date_to_string_convertor.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/app_bar.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/article_info.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/search_bar.dart
- aait/mobile/group-2/blog_app/pubspec.yaml
> feat(AAiT-mobile-2): Clean Up Homepage UI

- aait/mobile/group-2/blog_app/lib/core/presentation/theme/app_colors.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/article_card.dart
- aait/mobile/group-2/blog_app/lib/features/article/presentation/widgets/article_info.dart
> feat(AAiT-mobile-2): Make Some UI Changes

- aait/web/group-3/starter_project_group3/app/layout.tsx
- aait/web/group-3/starter_project_group3/app/profile/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/personalinformation/page.tsx
- aait/web/group-3/starter_project_group3/store/index.ts
- aait/web/group-3/starter_project_group3/store/update-personal-information/index.ts
- profile update is working including image upload feature for profile photo
> fit(AAiT-web_g3):add  profile update

- aait/web/group-2/app/blogs/[id]/page.tsx
- aait/web/group-2/app/blogs/page.tsx
- aait/web/group-2/components/blogs/BlogAuthor.tsx
- aait/web/group-2/components/blogs/BlogPreview.tsx
- aait/web/group-2/components/blogs/BlogTags.tsx
- aait/web/group-2/components/blogs/SearchArea.tsx
- aait/web/group-2/data/blog.ts
- aait/web/group-2/data/content.ts
> feat(AAiT-web-2): Blogs page and single blog page

- aait/web/group-3/starter_project_group3/app/login/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/accountsetting/page.tsx
- aait/web/group-3/starter_project_group3/app/profile/personalinformation/page.tsx
- aait/web/group-3/starter_project_group3/app/register/page.tsx
- aait/web/group-3/starter_project_group3/components/blog/SmallBlogCard.tsx
refinements on login, register and profile sections to show toast message.
simply I replace timeout function to wait 3 seconds with router.push() hook.
> fix(AAiT-web_g3): refinements on pages to show taost message

- aait/web/group-3/starter_project_group3/app/login/page.tsx
- aait/web/group-3/starter_project_group3/components/header/Header.tsx
- aait/web/group-3/starter_project_group3/components/header/NavBar.tsx
- aait/web/group-3/starter_project_group3/components/success-stories/StoriesSection.tsx
- aait/web/group-3/starter_project_group3/store/index.ts
- aait/web/group-3/starter_project_group3/store/user-Slice/index.ts
- login/register, logout, and profile icons are now in sync with user login status by using redux slice
- story section responsiveness fixed
> fix(AAiT-web_g3): sync login status with redux slice

- aait/web/group-3/starter_project_group3/app/globals.css
- aait/web/group-3/starter_project_group3/components/blog/Pagination.tsx
- aait/web/group-3/starter_project_group3/components/header/Header.tsx
- aait/web/group-3/starter_project_group3/hooks/usePagination.tsx
Fixed pagination bug
It used to render additional  unnecessary dots(...) and it's fixed now
> Fix(aait-web-3): Fix paginaiton
